import sqlite3
conn = sqlite3.connect('kaoyan_xt.db')
cur = conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
print('Tables:', cur.fetchall())
cur.execute("SELECT id, username FROM users")
print('Users:', cur.fetchall())
cur.execute("SELECT id, user_id, filename, subject FROM knowledge_documents")
print('Docs:', cur.fetchall())
conn.close()
