import os
import sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database import Base, engine, SessionLocal
from app.models.word import Word

CET4_WORDS = [
    ("abandon", "/əˈbændən/", "v. 放弃，抛弃", "He decided to abandon the project.", 1, 95, "高频词", "CET-4"),
    ("ability", "/əˈbɪləti/", "n. 能力，才能", "She has the ability to learn quickly.", 1, 88, "考纲词", "CET-4"),
    ("absolute", "/ˈæbsəluːt/", "adj. 绝对的，完全的", "This is an absolute truth.", 2, 75, "考纲词", "CET-4"),
    ("absorb", "/əbˈsɔːrb/", "v. 吸收；吸引", "Plants absorb carbon dioxide.", 2, 78, "考纲词", "CET-4"),
    ("academic", "/ˌækəˈdemɪk/", "adj. 学术的", "He has a strong academic background.", 2, 72, "考纲词", "CET-4"),
    ("accept", "/əkˈsept/", "v. 接受，认可", "She accepted the invitation.", 1, 90, "高频词", "CET-4"),
    ("access", "/ˈækses/", "n. 通道，入口；v. 访问", "Students have access to the library.", 2, 76, "考纲词", "CET-4"),
    ("accident", "/ˈæksɪdənt/", "n. 事故，意外", "There was a car accident.", 1, 85, "高频词", "CET-4"),
    ("achieve", "/əˈtʃiːv/", "v. 实现，达到", "She achieved great success.", 1, 86, "高频词", "CET-4"),
    ("acquire", "/əˈkwaɪər/", "v. 获得，取得", "He acquired a new skill.", 2, 73, "考纲词", "CET-4"),
    ("adapt", "/əˈdæpt/", "v. 适应，改编", "She quickly adapted to the new environment.", 2, 75, "考纲词", "CET-4"),
    ("addition", "/əˈdɪʃn/", "n. 增加，加法", "In addition, we need more time.", 1, 82, "高频词", "CET-4"),
    ("address", "/əˈdres/", "n. 地址；v. 演讲", "Please write your address here.", 1, 85, "高频词", "CET-4"),
    ("adjust", "/əˈdʒʌst/", "v. 调整，调节", "Please adjust the volume.", 2, 72, "考纲词", "CET-4"),
    ("admit", "/ədˈmɪt/", "v. 承认；允许进入", "He admitted his mistake.", 2, 76, "考纲词", "CET-4"),
    ("adopt", "/əˈdɑːpt/", "v. 采用，收养", "They decided to adopt a child.", 2, 70, "考纲词", "CET-4"),
    ("advance", "/ədˈvæns/", "v. 前进；n. 进展", "Technology has advanced rapidly.", 2, 78, "考纲词", "CET-4"),
    ("advantage", "/ədˈvæntɪdʒ/", "n. 优势，有利条件", "This gives us an advantage.", 1, 88, "高频词", "CET-4"),
    ("advice", "/ədˈvaɪs/", "n. 建议，忠告", "Can you give me some advice?", 1, 90, "高频词", "CET-4"),
    ("afford", "/əˈfɔːrd/", "v. 负担得起", "I can't afford this car.", 1, 86, "高频词", "CET-4"),
    ("alive", "/əˈlaɪv/", "adj. 活着的", "She is still alive.", 1, 88, "高频词", "CET-4"),
    ("allow", "/əˈlaʊ/", "v. 允许，准许", "Smoking is not allowed here.", 1, 88, "高频词", "CET-4"),
    ("alone", "/əˈloʊn/", "adj. 单独的；adv. 独自", "He lives alone.", 1, 90, "高频词", "CET-4"),
    ("along", "/əˈlɔːŋ/", "prep. 沿着；adv. 一起", "Walk along this street.", 1, 92, "高频词", "CET-4"),
    ("although", "/ɔːlˈðoʊ/", "conj. 虽然，尽管", "Although it rained, we went out.", 1, 90, "高频词", "CET-4"),
    ("amount", "/əˈmaʊnt/", "n. 数量；v. 合计", "A large amount of money was spent.", 2, 75, "考纲词", "CET-4"),
    ("analysis", "/əˈnæləsɪs/", "n. 分析", "The analysis shows interesting results.", 2, 72, "考纲词", "CET-4"),
    ("ancient", "/ˈeɪnʃənt/", "adj. 古代的", "This is an ancient city.", 2, 70, "考纲词", "CET-4"),
    ("announce", "/əˈnaʊns/", "v. 宣布，宣告", "They announced the winner.", 2, 72, "考纲词", "CET-4"),
    ("anxious", "/ˈæŋkʃəs/", "adj. 焦虑的，担心的", "He is anxious about the result.", 2, 72, "考纲词", "CET-4"),
    ("apologize", "/əˈpɑːlədʒaɪz/", "v. 道歉", "I apologize for my mistake.", 1, 85, "高频词", "CET-4"),
    ("appear", "/əˈpɪr/", "v. 出现，似乎", "He appeared to be happy.", 1, 88, "高频词", "CET-4"),
    ("apply", "/əˈplaɪ/", "v. 申请；应用", "I want to apply for this job.", 1, 88, "高频词", "CET-4"),
    ("appreciate", "/əˈpriːʃieɪt/", "v. 欣赏；感激", "I appreciate your help.", 2, 74, "考纲词", "CET-4"),
    ("approach", "/əˈproʊtʃ/", "v. 接近；n. 方法", "Winter is approaching.", 2, 75, "考纲词", "CET-4"),
    ("approve", "/əˈpruːv/", "v. 批准，赞成", "The committee approved the plan.", 2, 70, "考纲词", "CET-4"),
    ("arise", "/əˈraɪz/", "v. 出现，升起", "A problem has arisen.", 2, 72, "考纲词", "CET-4"),
    ("around", "/əˈraʊnd/", "prep. 围绕；adv. 大约", "There are around 100 people.", 1, 92, "高频词", "CET-4"),
    ("arrange", "/əˈreɪndʒ/", "v. 安排，整理", "I'll arrange a meeting.", 2, 72, "考纲词", "CET-4"),
    ("arrive", "/əˈraɪv/", "v. 到达", "We arrived at the station.", 1, 90, "高频词", "CET-4"),
    ("aspect", "/ˈæspekt/", "n. 方面，外观", "This is an important aspect.", 2, 74, "考纲词", "CET-4"),
    ("assign", "/əˈsaɪn/", "v. 分配，指派", "They assigned me a task.", 2, 70, "考纲词", "CET-4"),
    ("assist", "/əˈsɪst/", "v. 帮助，协助", "Can you assist me?", 2, 72, "考纲词", "CET-4"),
    ("associate", "/əˈsoʊʃieɪt/", "v. 联想；n. 同事", "I associate this song with my childhood.", 2, 72, "考纲词", "CET-4"),
    ("assume", "/əˈsuːm/", "v. 假定，承担", "Let's assume it's true.", 2, 74, "考纲词", "CET-4"),
    ("assure", "/əˈʃʊr/", "v. 保证，使确信", "I assure you it's safe.", 2, 70, "考纲词", "CET-4"),
    ("atmosphere", "/ˈætməsfɪr/", "n. 大气；氛围", "The atmosphere was tense.", 2, 72, "考纲词", "CET-4"),
    ("attach", "/əˈtætʃ/", "v. 附加，系", "Please attach your resume.", 2, 72, "考纲词", "CET-4"),
    ("attack", "/əˈtæk/", "v. 攻击；n. 攻击", "The dog attacked him.", 2, 74, "考纲词", "CET-4"),
    ("attempt", "/əˈtempt/", "v. 尝试；n. 尝试", "He attempted to climb the mountain.", 2, 72, "考纲词", "CET-4"),
    ("attend", "/əˈtend/", "v. 出席，参加", "I will attend the meeting.", 1, 86, "高频词", "CET-4"),
    ("attitude", "/ˈætɪtuːd/", "n. 态度", "Your attitude is important.", 2, 76, "考纲词", "CET-4"),
    ("attract", "/əˈtrækt/", "v. 吸引", "The bright colors attract attention.", 2, 74, "考纲词", "CET-4"),
    ("available", "/əˈveɪləbl/", "adj. 可用的，可获得的", "This room is available.", 2, 76, "考纲词", "CET-4"),
    ("average", "/ˈævərɪdʒ/", "n. 平均；adj. 平均的", "The average score is 85.", 2, 74, "考纲词", "CET-4"),
    ("avoid", "/əˈvɔɪd/", "v. 避免，避开", "Try to avoid mistakes.", 2, 76, "考纲词", "CET-4"),
    ("aware", "/əˈwer/", "adj. 意识到的", "Are you aware of the danger?", 2, 74, "考纲词", "CET-4"),
    ("background", "/ˈbækgraʊnd/", "n. 背景", "Tell me about your background.", 2, 74, "考纲词", "CET-4"),
    ("balance", "/ˈbæləns/", "n. 平衡；v. 平衡", "He lost his balance.", 2, 74, "考纲词", "CET-4"),
    ("base", "/beɪs/", "n. 基础；v. 以...为基础", "This is the base of the building.", 2, 76, "考纲词", "CET-4"),
    ("basic", "/ˈbeɪsɪk/", "adj. 基本的", "This is basic knowledge.", 2, 78, "考纲词", "CET-4"),
    ("basis", "/ˈbeɪsɪs/", "n. 基础，根据", "This is the basis of our theory.", 2, 74, "考纲词", "CET-4"),
    ("benefit", "/ˈbenɪfɪt/", "n. 利益；v. 有益于", "This will benefit everyone.", 2, 76, "考纲词", "CET-4"),
    ("belief", "/bɪˈliːf/", "n. 信仰，信念", "He has strong beliefs.", 2, 72, "考纲词", "CET-4"),
    ("believe", "/bɪˈliːv/", "v. 相信", "I believe in you.", 1, 92, "高频词", "CET-4"),
    ("belong", "/bɪˈlɔːŋ/", "v. 属于", "This book belongs to me.", 2, 74, "考纲词", "CET-4"),
    ("behavior", "/bɪˈheɪvjər/", "n. 行为，举止", "His behavior was strange.", 2, 74, "考纲词", "CET-4"),
    ("begin", "/bɪˈɡɪn/", "v. 开始", "Let's begin the meeting.", 1, 92, "高频词", "CET-4"),
    ("beyond", "/bɪˈjɑːnd/", "prep. 超越", "This is beyond my understanding.", 2, 72, "考纲词", "CET-4"),
    ("business", "/ˈbɪznəs/", "n. 商业，生意", "He is in business.", 1, 90, "高频词", "CET-4"),
    ("career", "/kəˈrɪr/", "n. 职业", "She has a successful career.", 2, 72, "考纲词", "CET-4"),
    ("change", "/tʃeɪndʒ/", "v. 改变；n. 变化", "Change is good.", 1, 95, "高频词", "CET-4"),
    ("character", "/ˈkærəktər/", "n. 性格；字符", "He has a good character.", 2, 74, "考纲词", "CET-4"),
    ("charge", "/tʃɑːrdʒ/", "v. 充电；n. 费用", "Charge your phone.", 2, 74, "考纲词", "CET-4"),
    ("community", "/kəˈmjuːnəti/", "n. 社区", "This is a friendly community.", 2, 72, "考纲词", "CET-4"),
    ("company", "/ˈkʌmpəni/", "n. 公司", "He works for a big company.", 1, 90, "高频词", "CET-4"),
    ("compare", "/kəmˈper/", "v. 比较", "Compare the two options.", 2, 72, "考纲词", "CET-4"),
    ("compete", "/kəmˈpiːt/", "v. 竞争", "They compete for the prize.", 2, 72, "考纲词", "CET-4"),
    ("complete", "/kəmˈpliːt/", "adj. 完整的；v. 完成", "Complete the task.", 2, 74, "考纲词", "CET-4"),
    ("computer", "/kəmˈpjuːtər/", "n. 计算机", "I use a computer.", 1, 92, "高频词", "CET-4"),
    ("concern", "/kənˈsɜːrn/", "n. 关注；v. 关心", "This is a concern.", 2, 74, "考纲词", "CET-4"),
    ("condition", "/kənˈdɪʃn/", "n. 条件；状况", "Under this condition...", 2, 74, "考纲词", "CET-4"),
    ("confirm", "/kənˈfɜːrm/", "v. 确认", "Please confirm your booking.", 2, 72, "考纲词", "CET-4"),
    ("conflict", "/ˈkɑːnflɪkt/", "n. 冲突；v. 冲突", "There was a conflict.", 2, 72, "考纲词", "CET-4"),
    ("connect", "/kəˈnekt/", "v. 连接", "Connect the two devices.", 2, 72, "考纲词", "CET-4"),
    ("consider", "/kənˈsɪdər/", "v. 考虑", "Consider your options.", 2, 74, "考纲词", "CET-4"),
    ("control", "/kənˈtrəʊl/", "v. 控制；n. 控制", "Control your temper.", 1, 92, "高频词", "CET-4"),
    ("create", "/kriˈeɪt/", "v. 创造", "Create something new.", 2, 74, "考纲词", "CET-4"),
    ("culture", "/ˈkʌltʃər/", "n. 文化", "Culture is important.", 2, 74, "考纲词", "CET-4"),
    ("current", "/ˈkʌrənt/", "adj. 当前的；n. 电流", "Current affairs.", 2, 74, "考纲词", "CET-4"),
    ("develop", "/dɪˈveləp/", "v. 发展", "Develop a plan.", 1, 92, "高频词", "CET-4"),
    ("different", "/ˈdɪfrənt/", "adj. 不同的", "Different ideas.", 1, 95, "高频词", "CET-4"),
    ("difficult", "/ˈdɪfɪkəlt/", "adj. 困难的", "It's difficult.", 1, 95, "高频词", "CET-4"),
    ("direction", "/daɪˈrekʃn/", "n. 方向", "Which direction?", 1, 92, "高频词", "CET-4"),
    ("discover", "/dɪˈskʌvər/", "v. 发现", "Discover a new planet.", 1, 92, "高频词", "CET-4"),
    ("document", "/ˈdɑːkjumənt/", "n. 文件；v. 记录", "Important document.", 2, 72, "考纲词", "CET-4"),
    ("economy", "/ɪˈkɑːnəmi/", "n. 经济", "National economy.", 2, 74, "考纲词", "CET-4"),
    ("education", "/ˌedʒuˈkeɪʃn/", "n. 教育", "Higher education.", 2, 76, "考纲词", "CET-4"),
    ("effect", "/ɪˈfekt/", "n. 效果", "Have an effect.", 1, 92, "高频词", "CET-4"),
    ("efficient", "/ɪˈfɪʃnt/", "adj. 高效的", "Efficient work.", 2, 72, "考纲词", "CET-4"),
    ("energy", "/ˈenərdʒi/", "n. 能量", "Save energy.", 2, 74, "考纲词", "CET-4"),
    ("environment", "/ɪnˈvaɪrənmənt/", "n. 环境", "Protect the environment.", 2, 74, "考纲词", "CET-4"),
    ("example", "/ɪɡˈzæmpl/", "n. 例子", "For example.", 1, 95, "高频词", "CET-4"),
    ("experience", "/ɪkˈspɪriəns/", "n. 经验；v. 经历", "Rich experience.", 2, 76, "考纲词", "CET-4"),
    ("express", "/ɪkˈspres/", "v. 表达", "Express your opinion.", 1, 92, "高频词", "CET-4"),
    ("face", "/feɪs/", "n. 脸；v. 面对", "Face the problem.", 1, 95, "高频词", "CET-4"),
    ("fact", "/fækt/", "n. 事实", "Tell me the fact.", 1, 95, "高频词", "CET-4"),
    ("factor", "/ˈfæktər/", "n. 因素", "Key factor.", 2, 72, "考纲词", "CET-4"),
    ("fail", "/feɪl/", "v. 失败", "Don't fail.", 1, 92, "高频词", "CET-4"),
    ("family", "/ˈfæməli/", "n. 家庭", "Happy family.", 1, 95, "高频词", "CET-4"),
    ("feature", "/ˈfiːtʃər/", "n. 特征", "Main feature.", 2, 72, "考纲词", "CET-4"),
    ("finance", "/ˈfaɪnæns/", "n. 金融", "Finance industry.", 2, 72, "考纲词", "CET-4"),
    ("find", "/faɪnd/", "v. 找到", "Find it.", 1, 95, "高频词", "CET-4"),
    ("finish", "/ˈfɪnɪʃ/", "v. 完成", "Finish the work.", 1, 95, "高频词", "CET-4"),
    ("follow", "/ˈfɑːloʊ/", "v. 跟随", "Follow me.", 1, 95, "高频词", "CET-4"),
    ("force", "/fɔːrs/", "n. 力量；v. 强迫", "Use force.", 2, 72, "考纲词", "CET-4"),
    ("form", "/fɔːrm/", "n. 形式；v. 形成", "Form a group.", 2, 72, "考纲词", "CET-4"),
    ("free", "/friː/", "adj. 自由的", "Free time.", 1, 95, "高频词", "CET-4"),
    ("function", "/ˈfʌŋkʃn/", "n. 功能", "Main function.", 2, 72, "考纲词", "CET-4"),
    ("future", "/ˈfjuːtʃər/", "n. 未来", "In the future.", 1, 92, "高频词", "CET-4"),
    ("general", "/ˈdʒenrəl/", "adj. 一般的", "General knowledge.", 2, 74, "考纲词", "CET-4"),
    ("global", "/ˈɡloʊbl/", "adj. 全球的", "Global warming.", 2, 74, "考纲词", "CET-4"),
    ("goal", "/ɡoʊl/", "n. 目标", "Achieve the goal.", 1, 92, "高频词", "CET-4"),
    ("good", "/ɡʊd/", "adj. 好的", "Good idea.", 1, 95, "高频词", "CET-4"),
    ("government", "/ˈɡʌvərnmənt/", "n. 政府", "Central government.", 2, 74, "考纲词", "CET-4"),
    ("great", "/ɡreɪt/", "adj. 伟大的", "Great achievement.", 1, 95, "高频词", "CET-4"),
    ("group", "/ɡruːp/", "n. 组；v. 分组", "Work in groups.", 1, 92, "高频词", "CET-4"),
    ("grow", "/ɡroʊ/", "v. 生长", "Grow quickly.", 1, 92, "高频词", "CET-4"),
    ("health", "/helθ/", "n. 健康", "Good health.", 2, 74, "考纲词", "CET-4"),
    ("help", "/help/", "v. 帮助", "Help me.", 1, 95, "高频词", "CET-4"),
    ("high", "/haɪ/", "adj. 高的", "High level.", 1, 95, "高频词", "CET-4"),
    ("history", "/ˈhɪstri/", "n. 历史", "World history.", 2, 72, "考纲词", "CET-4"),
    ("human", "/ˈhjuːmən/", "adj. 人类的", "Human nature.", 2, 74, "考纲词", "CET-4"),
    ("idea", "/aɪˈdɪə/", "n. 想法", "Good idea.", 1, 95, "高频词", "CET-4"),
    ("important", "/ɪmˈpɔːrtnt/", "adj. 重要的", "Important event.", 1, 95, "高频词", "CET-4"),
    ("improve", "/ɪmˈpruːv/", "v. 改善", "Improve skills.", 2, 74, "考纲词", "CET-4"),
    ("increase", "/ɪnˈkriːs/", "v. 增加", "Increase the number.", 2, 72, "考纲词", "CET-4"),
    ("industry", "/ˈɪndəstri/", "n. 工业；行业", "Service industry.", 2, 74, "考纲词", "CET-4"),
    ("information", "/ˌɪnfərˈmeɪʃn/", "n. 信息", "Useful information.", 2, 76, "考纲词", "CET-4"),
    ("institute", "/ˈɪnstɪtuːt/", "n. 机构", "Research institute.", 2, 72, "考纲词", "CET-4"),
    ("interest", "/ˈɪntrəst/", "n. 兴趣；v. 使感兴趣", "Show interest.", 1, 92, "高频词", "CET-4"),
    ("international", "/ˌɪntərˈnæʃənl/", "adj. 国际的", "International trade.", 2, 74, "考纲词", "CET-4"),
    ("job", "/dʒɑːb/", "n. 工作", "Good job.", 1, 95, "高频词", "CET-4"),
    ("knowledge", "/ˈnɑːlɪdʒ/", "n. 知识", "Gain knowledge.", 2, 76, "考纲词", "CET-4"),
    ("language", "/ˈlæŋɡwɪdʒ/", "n. 语言", "Foreign language.", 2, 74, "考纲词", "CET-4"),
    ("large", "/lɑːrdʒ/", "adj. 大的", "Large company.", 1, 95, "高频词", "CET-4"),
    ("learn", "/lɜːrn/", "v. 学习", "Learn English.", 1, 95, "高频词", "CET-4"),
    ("level", "/ˈlevl/", "n. 水平", "High level.", 2, 72, "考纲词", "CET-4"),
    ("limit", "/ˈlɪmɪt/", "n. 限制；v. 限制", "Set a limit.", 2, 72, "考纲词", "CET-4"),
    ("local", "/ˈloʊkl/", "adj. 本地的", "Local news.", 2, 72, "考纲词", "CET-4"),
    ("long", "/lɔːŋ/", "adj. 长的", "Long time.", 1, 95, "高频词", "CET-4"),
    ("major", "/ˈmeɪdʒər/", "adj. 主要的", "Major problem.", 2, 74, "考纲词", "CET-4"),
    ("make", "/meɪk/", "v. 制作", "Make a plan.", 1, 95, "高频词", "CET-4"),
    ("manage", "/ˈmænɪdʒ/", "v. 管理", "Manage a team.", 2, 74, "考纲词", "CET-4"),
    ("market", "/ˈmɑːrkɪt/", "n. 市场", "Stock market.", 2, 74, "考纲词", "CET-4"),
    ("may", "/meɪ/", "v. 可能；可以", "You may go.", 1, 95, "高频词", "CET-4"),
    ("mean", "/miːn/", "v. 意味着", "What does it mean?", 1, 95, "高频词", "CET-4"),
    ("meeting", "/ˈmiːtɪŋ/", "n. 会议", "Business meeting.", 2, 72, "考纲词", "CET-4"),
    ("member", "/ˈmembər/", "n. 成员", "Team member.", 2, 72, "考纲词", "CET-4"),
    ("method", "/ˈmeθəd/", "n. 方法", "New method.", 2, 74, "考纲词", "CET-4"),
    ("middle", "/ˈmɪdl/", "adj. 中间的", "Middle school.", 1, 92, "高频词", "CET-4"),
    ("might", "/maɪt/", "v. 可能", "He might come.", 1, 95, "高频词", "CET-4"),
    ("mind", "/maɪnd/", "n. 思想；v. 介意", "Change your mind.", 1, 92, "高频词", "CET-4"),
    ("money", "/ˈmʌni/", "n. 钱", "Make money.", 1, 95, "高频词", "CET-4"),
    ("more", "/mɔːr/", "adj. 更多的", "More information.", 1, 95, "高频词", "CET-4"),
    ("must", "/mʌst/", "v. 必须", "You must do it.", 1, 95, "高频词", "CET-4"),
    ("need", "/niːd/", "v. 需要", "I need help.", 1, 95, "高频词", "CET-4"),
    ("never", "/ˈnevər/", "adv. 从不", "Never give up.", 1, 95, "高频词", "CET-4"),
    ("new", "/nuː/", "adj. 新的", "New idea.", 1, 95, "高频词", "CET-4"),
    ("now", "/naʊ/", "adv. 现在", "Now is the time.", 1, 95, "高频词", "CET-4"),
    ("number", "/ˈnʌmbər/", "n. 数字", "Large number.", 1, 92, "高频词", "CET-4"),
    ("old", "/oʊld/", "adj. 老的", "Old man.", 1, 95, "高频词", "CET-4"),
    ("only", "/ˈoʊnli/", "adv. 只有", "Only you.", 1, 95, "高频词", "CET-4"),
    ("open", "/ˈoʊpən/", "v. 打开；adj. 开的", "Open the door.", 1, 95, "高频词", "CET-4"),
    ("order", "/ˈɔːrdər/", "n. 顺序；v. 订购", "In order.", 1, 92, "高频词", "CET-4"),
    ("other", "/ˈʌðər/", "adj. 其他的", "Other people.", 1, 95, "高频词", "CET-4"),
    ("part", "/pɑːrt/", "n. 部分", "Part of the plan.", 1, 92, "高频词", "CET-4"),
    ("pass", "/pæs/", "v. 通过", "Pass the exam.", 1, 92, "高频词", "CET-4"),
    ("people", "/ˈpiːpl/", "n. 人们", "Many people.", 1, 95, "高频词", "CET-4"),
    ("place", "/pleɪs/", "n. 地方", "Nice place.", 1, 95, "高频词", "CET-4"),
    ("plan", "/plæn/", "n. 计划；v. 计划", "Make a plan.", 1, 92, "高频词", "CET-4"),
    ("point", "/pɔɪnt/", "n. 点；v. 指", "Good point.", 1, 92, "高频词", "CET-4"),
    ("possible", "/ˈpɑːsəbl/", "adj. 可能的", "Is it possible?", 1, 92, "高频词", "CET-4"),
    ("power", "/ˈpaʊər/", "n. 力量；权力", "Power of knowledge.", 2, 74, "考纲词", "CET-4"),
    ("problem", "/ˈprɑːbləm/", "n. 问题", "Solve the problem.", 1, 95, "高频词", "CET-4"),
    ("process", "/ˈprɑːses/", "n. 过程", "The process of learning.", 2, 74, "考纲词", "CET-4"),
    ("product", "/ˈprɑːdʌkt/", "n. 产品", "New product.", 2, 74, "考纲词", "CET-4"),
    ("provide", "/prəˈvaɪd/", "v. 提供", "Provide help.", 2, 74, "考纲词", "CET-4"),
    ("public", "/ˈpʌblɪk/", "adj. 公共的", "Public transport.", 2, 74, "考纲词", "CET-4"),
    ("quality", "/ˈkwɑːləti/", "n. 质量", "Good quality.", 2, 74, "考纲词", "CET-4"),
    ("question", "/ˈkwestʃən/", "n. 问题", "Answer the question.", 1, 92, "高频词", "CET-4"),
    ("quick", "/kwɪk/", "adj. 快的", "Quick response.", 1, 92, "高频词", "CET-4"),
    ("right", "/raɪt/", "adj. 正确的", "You are right.", 1, 95, "高频词", "CET-4"),
    ("run", "/rʌn/", "v. 跑", "Run fast.", 1, 95, "高频词", "CET-4"),
    ("same", "/seɪm/", "adj. 相同的", "Same result.", 1, 95, "高频词", "CET-4"),
    ("school", "/skuːl/", "n. 学校", "High school.", 1, 95, "高频词", "CET-4"),
    ("science", "/ˈsaɪəns/", "n. 科学", "Natural science.", 2, 74, "考纲词", "CET-4"),
    ("search", "/sɜːrtʃ/", "v. 搜索", "Search for information.", 2, 72, "考纲词", "CET-4"),
    ("second", "/ˈsekənd/", "n. 秒；adj. 第二", "Second place.", 1, 95, "高频词", "CET-4"),
    ("send", "/send/", "v. 发送", "Send an email.", 1, 92, "高频词", "CET-4"),
    ("service", "/ˈsɜːrvɪs/", "n. 服务", "Customer service.", 2, 74, "考纲词", "CET-4"),
    ("set", "/set/", "v. 设置", "Set a goal.", 1, 92, "高频词", "CET-4"),
    ("show", "/ʃoʊ/", "v. 展示", "Show me.", 1, 95, "高频词", "CET-4"),
    ("small", "/smɔːl/", "adj. 小的", "Small house.", 1, 95, "高频词", "CET-4"),
    ("social", "/ˈsoʊʃl/", "adj. 社会的", "Social media.", 2, 74, "考纲词", "CET-4"),
    ("some", "/sʌm/", "adj. 一些", "Some people.", 1, 95, "高频词", "CET-4"),
    ("soon", "/suːn/", "adv. 很快", "See you soon.", 1, 95, "高频词", "CET-4"),
    ("state", "/steɪt/", "n. 状态；州", "State of matter.", 2, 72, "考纲词", "CET-4"),
    ("study", "/ˈstʌdi/", "v. 学习；n. 研究", "Study hard.", 1, 95, "高频词", "CET-4"),
    ("system", "/ˈsɪstəm/", "n. 系统", "Computer system.", 2, 74, "考纲词", "CET-4"),
    ("take", "/teɪk/", "v. 拿；采取", "Take a break.", 1, 95, "高频词", "CET-4"),
    ("task", "/tæsk/", "n. 任务", "Complete the task.", 2, 72, "考纲词", "CET-4"),
    ("team", "/tiːm/", "n. 团队", "Work as a team.", 1, 92, "高频词", "CET-4"),
    ("technology", "/tekˈnɑːlədʒi/", "n. 技术", "New technology.", 2, 74, "考纲词", "CET-4"),
    ("tell", "/tel/", "v. 告诉", "Tell me.", 1, 95, "高频词", "CET-4"),
    ("think", "/θɪŋk/", "v. 思考", "Think carefully.", 1, 95, "高频词", "CET-4"),
    ("time", "/taɪm/", "n. 时间", "Good time.", 1, 95, "高频词", "CET-4"),
    ("today", "/təˈdeɪ/", "n. 今天", "Today is Monday.", 1, 95, "高频词", "CET-4"),
    ("too", "/tuː/", "adv. 也；太", "Me too.", 1, 95, "高频词", "CET-4"),
    ("try", "/traɪ/", "v. 尝试", "Try again.", 1, 95, "高频词", "CET-4"),
    ("turn", "/tɜːrn/", "v. 转动", "Turn right.", 1, 95, "高频词", "CET-4"),
    ("two", "/tuː/", "num. 二", "Two people.", 1, 95, "高频词", "CET-4"),
    ("under", "/ˈʌndər/", "prep. 在...下面", "Under the table.", 1, 95, "高频词", "CET-4"),
    ("understand", "/ˌʌndərˈstænd/", "v. 理解", "I understand.", 1, 95, "高频词", "CET-4"),
    ("university", "/ˌjuːnɪˈvɜːrsəti/", "n. 大学", "State university.", 2, 74, "考纲词", "CET-4"),
    ("use", "/juːz/", "v. 使用", "Use computer.", 1, 95, "高频词", "CET-4"),
    ("very", "/ˈveri/", "adv. 非常", "Very good.", 1, 95, "高频词", "CET-4"),
    ("view", "/vjuː/", "n. 观点；v. 查看", "Different view.", 2, 72, "考纲词", "CET-4"),
    ("want", "/wɑːnt/", "v. 想要", "I want it.", 1, 95, "高频词", "CET-4"),
    ("way", "/weɪ/", "n. 方式", "Good way.", 1, 95, "高频词", "CET-4"),
    ("week", "/wiːk/", "n. 周", "Next week.", 1, 95, "高频词", "CET-4"),
    ("well", "/wel/", "adv. 好", "Well done.", 1, 95, "高频词", "CET-4"),
    ("when", "/wen/", "adv. 什么时候", "When is it?", 1, 95, "高频词", "CET-4"),
    ("which", "/wɪtʃ/", "adj. 哪个", "Which one?", 1, 95, "高频词", "CET-4"),
    ("who", "/huː/", "pron. 谁", "Who is it?", 1, 95, "高频词", "CET-4"),
    ("why", "/waɪ/", "adv. 为什么", "Why not?", 1, 95, "高频词", "CET-4"),
    ("will", "/wɪl/", "v. 将", "I will go.", 1, 95, "高频词", "CET-4"),
    ("work", "/wɜːrk/", "v. 工作", "Work hard.", 1, 95, "高频词", "CET-4"),
    ("world", "/wɜːrld/", "n. 世界", "The world is big.", 1, 95, "高频词", "CET-4"),
    ("year", "/jɪr/", "n. 年", "Last year.", 1, 95, "高频词", "CET-4"),
    ("yes", "/jes/", "adv. 是", "Yes, I do.", 1, 95, "高频词", "CET-4"),
    ("yet", "/jet/", "adv. 还", "Not yet.", 1, 92, "高频词", "CET-4"),
    ("you", "/juː/", "pron. 你", "You are here.", 1, 95, "高频词", "CET-4"),
    ("your", "/jʊr/", "adj. 你的", "Your book.", 1, 95, "高频词", "CET-4"),
]

CET6_WORDS = [
    ("abnormal", "/æbˈnɔːrml/", "adj. 异常的，反常的", "This is an abnormal situation.", 3, 65, "考纲词", "CET-6"),
    ("abolish", "/əˈbɑːlɪʃ/", "v. 废除，取消", "They decided to abolish the law.", 3, 68, "考纲词", "CET-6"),
    ("abrupt", "/əˈbrʌpt/", "adj. 突然的，粗鲁的", "There was an abrupt change.", 3, 68, "考纲词", "CET-6"),
    ("absurd", "/əbˈsɜːrd/", "adj. 荒谬的", "This is an absurd idea.", 3, 68, "考纲词", "CET-6"),
    ("abundance", "/əˈbʌndəns/", "n. 丰富，充裕", "There is an abundance of food.", 3, 68, "考纲词", "CET-6"),
    ("accelerate", "/əkˈseləreɪt/", "v. 加速", "The car accelerated.", 3, 72, "考纲词", "CET-6"),
    ("accessory", "/əkˈsesəri/", "n. 附件，配饰", "She wore accessories.", 3, 65, "考纲词", "CET-6"),
    ("accommodate", "/əˈkɑːmədeɪt/", "v. 容纳；适应", "The hotel can accommodate guests.", 3, 72, "考纲词", "CET-6"),
    ("acknowledge", "/əkˈnɑːlɪdʒ/", "v. 承认；感谢", "He acknowledged the help.", 3, 72, "考纲词", "CET-6"),
    ("acquaint", "/əˈkweɪnt/", "v. 使熟悉", "I am acquainted with him.", 3, 68, "考纲词", "CET-6"),
    ("acquisition", "/ˌækwɪˈzɪʃn/", "n. 获得，收购", "The acquisition was successful.", 3, 70, "考纲词", "CET-6"),
    ("activate", "/ˈæktɪveɪt/", "v. 激活", "Activate the device.", 3, 70, "考纲词", "CET-6"),
    ("acute", "/əˈkjuːt/", "adj. 严重的；急性的", "This is an acute problem.", 3, 72, "考纲词", "CET-6"),
    ("adhere", "/ədˈhɪr/", "v. 坚持；粘附", "Adhere to the rules.", 3, 70, "考纲词", "CET-6"),
    ("adjacent", "/əˈdʒeɪsənt/", "adj. 相邻的", "The building is adjacent.", 3, 68, "考纲词", "CET-6"),
    ("administer", "/ədˈmɪnɪstər/", "v. 管理；执行", "Administer the program.", 3, 70, "考纲词", "CET-6"),
    ("adolescent", "/ˌædəˈlesnt/", "n. 青少年", "Adolescent behavior.", 3, 68, "考纲词", "CET-6"),
    ("advocate", "/ˈædvəkət/", "n. 倡导者；v. 倡导", "He advocates for change.", 3, 72, "考纲词", "CET-6"),
    ("aesthetic", "/iːsˈθetɪk/", "adj. 审美的", "Aesthetic value.", 3, 68, "考纲词", "CET-6"),
    ("affiliate", "/əˈfɪlieɪt/", "v. 隶属", "The company is affiliated.", 3, 68, "考纲词", "CET-6"),
    ("affirm", "/əˈfɜːrm/", "v. 确认，断言", "He affirmed his commitment.", 3, 70, "考纲词", "CET-6"),
    ("afflict", "/əˈflɪkt/", "v. 折磨", "He is afflicted by disease.", 3, 66, "考纲词", "CET-6"),
    ("affluent", "/ˈæfluənt/", "adj. 富裕的", "An affluent neighborhood.", 3, 68, "考纲词", "CET-6"),
    ("aggravate", "/ˈæɡrəveɪt/", "v. 加重，恶化", "This aggravates the problem.", 3, 68, "考纲词", "CET-6"),
    ("aggregate", "/ˈæɡrɪɡət/", "n. 总数", "The aggregate amount.", 3, 70, "考纲词", "CET-6"),
    ("agitation", "/ˌædʒɪˈteɪʃn/", "n. 激动；搅动", "There was much agitation.", 3, 66, "考纲词", "CET-6"),
    ("agony", "/ˈæɡəni/", "n. 痛苦", "He was in agony.", 3, 66, "考纲词", "CET-6"),
    ("aggressive", "/əˈɡresɪv/", "adj. 侵略的；积极的", "An aggressive approach.", 3, 70, "考纲词", "CET-6"),
    ("alert", "/əˈlɜːrt/", "adj. 警觉的；v. 提醒", "Stay alert.", 3, 70, "考纲词", "CET-6"),
    ("alien", "/ˈeɪliən/", "adj. 外国的；n. 外国人", "An alien culture.", 3, 68, "考纲词", "CET-6"),
    ("allege", "/əˈledʒ/", "v. 指控，声称", "He alleged the facts.", 3, 68, "考纲词", "CET-6"),
    ("alleviate", "/əˈliːvieɪt/", "v. 减轻，缓解", "Alleviate the pain.", 3, 70, "考纲词", "CET-6"),
    ("alliance", "/əˈlaɪəns/", "n. 联盟", "Form an alliance.", 3, 70, "考纲词", "CET-6"),
    ("allocate", "/ˈæləkeɪt/", "v. 分配，分派", "Allocate resources.", 3, 70, "考纲词", "CET-6"),
    ("allowance", "/əˈlaʊəns/", "n. 津贴，允许", "Monthly allowance.", 3, 68, "考纲词", "CET-6"),
    ("allude", "/əˈluːd/", "v. 暗指", "He alluded to the problem.", 3, 66, "考纲词", "CET-6"),
    ("allure", "/əˈlʊr/", "n. 诱惑；v. 吸引", "The allure of money.", 3, 68, "考纲词", "CET-6"),
    ("ally", "/ˈælaɪ/", "n. 盟友；v. 结盟", "Political ally.", 3, 68, "考纲词", "CET-6"),
    ("alternate", "/ˈɔːltərnət/", "v. 交替；adj. 交替的", "Alternate days.", 3, 70, "考纲词", "CET-6"),
    ("alternative", "/ɔːlˈtɜːrnətɪv/", "n. 替代物", "There is no alternative.", 3, 72, "考纲词", "CET-6"),
    ("altitude", "/ˈæltɪtuːd/", "n. 高度，海拔", "High altitude.", 3, 68, "考纲词", "CET-6"),
    ("amateur", "/ˈæmətər/", "n. 业余爱好者", "An amateur painter.", 3, 68, "考纲词", "CET-6"),
    ("ambassador", "/æmˈbæsədər/", "n. 大使", "Ambassador to China.", 3, 68, "考纲词", "CET-6"),
    ("ambiguous", "/æmˈbɪɡjuəs/", "adj. 模棱两可的", "Ambiguous statement.", 3, 72, "考纲词", "CET-6"),
    ("ambitious", "/æmˈbɪʃəs/", "adj. 有野心的", "An ambitious plan.", 3, 70, "考纲词", "CET-6"),
    ("amplify", "/ˈæmplɪfaɪ/", "v. 放大", "Amplify the sound.", 3, 70, "考纲词", "CET-6"),
    ("analogous", "/əˈnæləɡəs/", "adj. 类似的", "Analogous situation.", 3, 70, "考纲词", "CET-6"),
    ("analogy", "/əˈnælədʒi/", "n. 类比", "Draw an analogy.", 3, 70, "考纲词", "CET-6"),
    ("analytical", "/ˌænəˈlɪtɪkl/", "adj. 分析的", "Analytical skills.", 3, 72, "考纲词", "CET-6"),
    ("anecdote", "/ˈænɪkdoʊt/", "n. 轶事", "Interesting anecdote.", 3, 68, "考纲词", "CET-6"),
    ("anguish", "/ˈæŋɡwɪʃ/", "n. 痛苦", "Mental anguish.", 3, 66, "考纲词", "CET-6"),
    ("animated", "/ˈænɪmeɪtɪd/", "adj. 生动的", "Animated discussion.", 3, 70, "考纲词", "CET-6"),
    ("animation", "/ˌænɪˈmeɪʃn/", "n. 动画", "Computer animation.", 3, 70, "考纲词", "CET-6"),
    ("annotate", "/ˈænəteɪt/", "v. 注释", "Annotate the text.", 3, 68, "考纲词", "CET-6"),
    ("anonymous", "/əˈnɑːnɪməs/", "adj. 匿名的", "Anonymous letter.", 3, 70, "考纲词", "CET-6"),
    ("antagonize", "/ænˈtæɡənaɪz/", "v. 使敌对", "Don't antagonize him.", 3, 66, "考纲词", "CET-6"),
    ("antecedent", "/ˌæntɪˈsiːdnt/", "n. 前因", "Historical antecedent.", 3, 68, "考纲词", "CET-6"),
    ("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期", "Anticipate success.", 3, 72, "考纲词", "CET-6"),
    ("antique", "/ænˈtiːk/", "adj. 古老的；n. 古董", "Antique furniture.", 3, 68, "考纲词", "CET-6"),
    ("antisocial", "/ˌæntiˈsoʊʃl/", "adj. 反社会的", "Antisocial behavior.", 3, 68, "考纲词", "CET-6"),
    ("anxiety", "/æŋˈzaɪəti/", "n. 焦虑", "Anxiety about exams.", 3, 70, "考纲词", "CET-6"),
    ("apex", "/ˈeɪpeks/", "n. 顶点", "The apex of career.", 3, 66, "考纲词", "CET-6"),
    ("apparatus", "/ˌæpəˈrætəs/", "n. 器械", "Medical apparatus.", 3, 66, "考纲词", "CET-6"),
    ("appeal", "/əˈpiːl/", "n. 呼吁；v. 吸引", "The idea appeals to me.", 3, 72, "考纲词", "CET-6"),
    ("appetite", "/ˈæpɪtaɪt/", "n. 食欲", "Good appetite.", 3, 68, "考纲词", "CET-6"),
    ("applaud", "/əˈplɔːd/", "v. 鼓掌", "Audience applauded.", 3, 68, "考纲词", "CET-6"),
    ("applicable", "/ˈæplɪkəbl/", "adj. 适用的", "Applicable rules.", 3, 70, "考纲词", "CET-6"),
    ("appoint", "/əˈpɔɪnt/", "v. 任命", "Appoint a manager.", 3, 70, "考纲词", "CET-6"),
    ("appraisal", "/əˈpreɪzl/", "n. 评估", "Performance appraisal.", 3, 70, "考纲词", "CET-6"),
    ("apprehensive", "/ˌæprɪˈhensɪv/", "adj. 担心的", "Apprehensive about future.", 3, 70, "考纲词", "CET-6"),
    ("apprentice", "/əˈprentɪs/", "n. 学徒", "Young apprentice.", 3, 66, "考纲词", "CET-6"),
    ("aptitude", "/ˈæptɪtuːd/", "n. 才能", "Natural aptitude.", 3, 70, "考纲词", "CET-6"),
    ("architect", "/ˈɑːrkɪtekt/", "n. 建筑师", "Famous architect.", 3, 68, "考纲词", "CET-6"),
    ("architecture", "/ˈɑːrkɪtektʃər/", "n. 建筑", "Modern architecture.", 3, 70, "考纲词", "CET-6"),
    ("ardent", "/ˈɑːrdnt/", "adj. 热情的", "Ardent supporter.", 3, 68, "考纲词", "CET-6"),
    ("arithmetic", "/əˈrɪθmətɪk/", "n. 算术", "Basic arithmetic.", 3, 68, "考纲词", "CET-6"),
    ("armament", "/ˈɑːrməmənt/", "n. 武器", "Military armament.", 3, 66, "考纲词", "CET-6"),
    ("armor", "/ˈɑːrmər/", "n. 盔甲", "Knights armor.", 3, 66, "考纲词", "CET-6"),
    ("arouse", "/əˈraʊz/", "v. 唤起", "Arouse interest.", 3, 70, "考纲词", "CET-6"),
    ("array", "/əˈreɪ/", "n. 阵列", "Array of data.", 3, 70, "考纲词", "CET-6"),
    ("arrest", "/əˈrest/", "v. 逮捕", "Police arrested him.", 3, 70, "考纲词", "CET-6"),
    ("arrival", "/əˈraɪvl/", "n. 到达", "His arrival was unexpected.", 3, 68, "考纲词", "CET-6"),
    ("arrogant", "/ˈærəɡənt/", "adj. 傲慢的", "Arrogant attitude.", 3, 70, "考纲词", "CET-6"),
    ("arsenal", "/ˈɑːrsənl/", "n. 军火库", "Military arsenal.", 3, 66, "考纲词", "CET-6"),
    ("arson", "/ˈɑːrsən/", "n. 纵火", "Arson attack.", 3, 65, "考纲词", "CET-6"),
    ("artificial", "/ˌɑːrtɪˈfɪʃl/", "adj. 人造的", "Artificial intelligence.", 3, 72, "考纲词", "CET-6"),
    ("artifact", "/ˈɑːrtɪfækt/", "n. 人工制品", "Ancient artifact.", 3, 68, "考纲词", "CET-6"),
    ("artisan", "/ˈɑːrtəzn/", "n. 工匠", "Skilled artisan.", 3, 66, "考纲词", "CET-6"),
    ("articulate", "/ɑːrˈtɪkjəleɪt/", "v. 清晰表达", "Articulate your ideas.", 3, 72, "考纲词", "CET-6"),
    ("artistic", "/ɑːrˈtɪstɪk/", "adj. 艺术的", "Artistic talent.", 3, 70, "考纲词", "CET-6"),
    ("ascend", "/əˈsend/", "v. 上升", "Ascend the mountain.", 3, 68, "考纲词", "CET-6"),
    ("ascertain", "/ˌæsərˈteɪn/", "v. 确定", "Ascertain the facts.", 3, 70, "考纲词", "CET-6"),
    ("ascribe", "/əˈskraɪb/", "v. 归因于", "Ascribe to effort.", 3, 70, "考纲词", "CET-6"),
    ("ashamed", "/əˈʃeɪmd/", "adj. 羞愧的", "Feel ashamed.", 3, 68, "考纲词", "CET-6"),
    ("aspiration", "/ˌæspəˈreɪʃn/", "n. 抱负", "Career aspiration.", 3, 70, "考纲词", "CET-6"),
    ("aspire", "/əˈspaɪər/", "v. 渴望", "Aspire to succeed.", 3, 70, "考纲词", "CET-6"),
    ("assassinate", "/əˈsæsəneɪt/", "v. 暗杀", "Assassinate the leader.", 3, 66, "考纲词", "CET-6"),
    ("assault", "/əˈsɔːlt/", "n. 攻击", "Physical assault.", 3, 68, "考纲词", "CET-6"),
    ("assemble", "/əˈsembl/", "v. 集合", "Workers assemble cars.", 3, 70, "考纲词", "CET-6"),
    ("assembly", "/əˈsembli/", "n. 集会", "The assembly took place.", 3, 68, "考纲词", "CET-6"),
    ("assert", "/əˈsɜːrt/", "v. 断言", "Assert his innocence.", 3, 70, "考纲词", "CET-6"),
    ("assess", "/əˈses/", "v. 评估", "Assess the damage.", 3, 70, "考纲词", "CET-6"),
    ("asset", "/ˈæset/", "n. 资产", "Financial asset.", 3, 70, "考纲词", "CET-6"),
    ("assimilate", "/əˈsɪməleɪt/", "v. 吸收", "Assimilate knowledge.", 3, 70, "考纲词", "CET-6"),
    ("assorted", "/əˈsɔːrtɪd/", "adj. 各种各样的", "Assorted goods.", 3, 68, "考纲词", "CET-6"),
    ("astound", "/əˈstaʊnd/", "v. 使震惊", "The news astounded us.", 3, 68, "考纲词", "CET-6"),
    ("astronaut", "/ˈæstrənɔːt/", "n. 宇航员", "Space astronaut.", 3, 68, "考纲词", "CET-6"),
    ("astronomy", "/əˈstrɑːnəmi/", "n. 天文学", "Study astronomy.", 3, 68, "考纲词", "CET-6"),
    ("asylum", "/əˈsaɪləm/", "n. 庇护", "Political asylum.", 3, 66, "考纲词", "CET-6"),
    ("atlas", "/ˈætləs/", "n. 地图集", "World atlas.", 3, 66, "考纲词", "CET-6"),
    ("atomic", "/əˈtɒmɪk/", "adj. 原子的", "Atomic energy.", 3, 70, "考纲词", "CET-6"),
    ("attain", "/əˈteɪn/", "v. 达到", "Attain the goal.", 3, 70, "考纲词", "CET-6"),
    ("attentive", "/əˈtentɪv/", "adj. 专心的", "Attentive student.", 3, 70, "考纲词", "CET-6"),
    ("attorney", "/əˈtɜːrni/", "n. 律师", "Legal attorney.", 3, 68, "考纲词", "CET-6"),
    ("attribute", "/əˈtrɪbjuːt/", "v. 归因于", "Attribute to success.", 3, 72, "考纲词", "CET-6"),
    ("audit", "/ˈɔːdɪt/", "n. 审计；v. 审计", "Financial audit.", 3, 70, "考纲词", "CET-6"),
    ("auditorium", "/ˌɔːdɪˈtɔːriəm/", "n. 礼堂", "School auditorium.", 3, 66, "考纲词", "CET-6"),
    ("augment", "/ɔːɡˈment/", "v. 增加", "Augment resources.", 3, 68, "考纲词", "CET-6"),
    ("authority", "/əˈθɔːrəti/", "n. 权威", "Local authority.", 3, 70, "考纲词", "CET-6"),
    ("autonomous", "/ɔːˈtɑːnəməs/", "adj. 自治的", "Autonomous region.", 3, 70, "考纲词", "CET-6"),
    ("autobiography", "/ˌɔːtəbaɪˈɒɡrəfi/", "n. 自传", "Write an autobiography.", 3, 66, "考纲词", "CET-6"),
    ("automate", "/ˈɔːtəmeɪt/", "v. 自动化", "Automate the process.", 3, 70, "考纲词", "CET-6"),
    ("autopsy", "/ˈɔːtɑːpsi/", "n. 验尸", "Medical autopsy.", 3, 65, "考纲词", "CET-6"),
    ("avail", "/əˈveɪl/", "v. 利用", "Avail yourself of the opportunity.", 3, 66, "考纲词", "CET-6"),
    ("availability", "/əˌveɪləˈbɪləti/", "n. 可用性", "Check availability.", 3, 68, "考纲词", "CET-6"),
    ("avert", "/əˈvɜːrt/", "v. 避免", "Avert disaster.", 3, 66, "考纲词", "CET-6"),
    ("aviation", "/ˌeɪviˈeɪʃn/", "n. 航空", "Civil aviation.", 3, 68, "考纲词", "CET-6"),
    ("avoidance", "/əˈvɔɪdns/", "n. 避免", "Conflict avoidance.", 3, 66, "考纲词", "CET-6"),
]

GRADUATE_WORDS = [
    ("abide", "/əˈbaɪd/", "v. 遵守；忍受", "Abide by the rules.", 3, 68, "考纲词", "考研"),
    ("abound", "/əˈbaʊnd/", "v. 大量存在", "Fish abound in the lake.", 3, 66, "考纲词", "考研"),
    ("abrupt", "/əˈbrʌpt/", "adj. 突然的", "An abrupt change.", 3, 68, "考纲词", "考研"),
    ("absurd", "/əbˈsɜːrd/", "adj. 荒谬的", "Absurd idea.", 3, 68, "考纲词", "考研"),
    ("abundance", "/əˈbʌndəns/", "n. 丰富", "Abundance of resources.", 3, 68, "考纲词", "考研"),
    ("academic", "/ˌækəˈdemɪk/", "adj. 学术的", "Academic research.", 3, 70, "考纲词", "考研"),
    ("accommodate", "/əˈkɑːmədeɪt/", "v. 容纳", "Accommodate guests.", 3, 72, "考纲词", "考研"),
    ("acknowledge", "/əkˈnɑːlɪdʒ/", "v. 承认", "Acknowledge the mistake.", 3, 72, "考纲词", "考研"),
    ("acquaint", "/əˈkweɪnt/", "v. 使熟悉", "Acquaint oneself with.", 3, 68, "考纲词", "考研"),
    ("acquisition", "/ˌækwɪˈzɪʃn/", "n. 获得", "Language acquisition.", 3, 70, "考纲词", "考研"),
    ("activate", "/ˈæktɪveɪt/", "v. 激活", "Activate the system.", 3, 70, "考纲词", "考研"),
    ("acute", "/əˈkjuːt/", "adj. 严重的", "Acute problem.", 3, 72, "考纲词", "考研"),
    ("adhere", "/ədˈhɪr/", "v. 坚持", "Adhere to principles.", 3, 70, "考纲词", "考研"),
    ("adjacent", "/əˈdʒeɪsənt/", "adj. 相邻的", "Adjacent buildings.", 3, 68, "考纲词", "考研"),
    ("administer", "/ədˈmɪnɪstər/", "v. 管理", "Administer the program.", 3, 70, "考纲词", "考研"),
    ("adolescent", "/ˌædəˈlesnt/", "n. 青少年", "Adolescent development.", 3, 68, "考纲词", "考研"),
    ("advocate", "/ˈædvəkət/", "v. 倡导", "Advocate for reform.", 3, 72, "考纲词", "考研"),
    ("aesthetic", "/iːsˈθetɪk/", "adj. 审美的", "Aesthetic value.", 3, 68, "考纲词", "考研"),
    ("affirm", "/əˈfɜːrm/", "v. 确认", "Affirm one's belief.", 3, 70, "考纲词", "考研"),
    ("afflict", "/əˈflɪkt/", "v. 折磨", "Afflicted by disease.", 3, 66, "考纲词", "考研"),
    ("affluent", "/ˈæfluənt/", "adj. 富裕的", "Affluent society.", 3, 68, "考纲词", "考研"),
    ("aggravate", "/ˈæɡrəveɪt/", "v. 加重", "Aggravate the situation.", 3, 68, "考纲词", "考研"),
    ("agitation", "/ˌædʒɪˈteɪʃn/", "n. 激动", "Public agitation.", 3, 66, "考纲词", "考研"),
    ("agony", "/ˈæɡəni/", "n. 痛苦", "Agony of defeat.", 3, 66, "考纲词", "考研"),
    ("aggressive", "/əˈɡresɪv/", "adj. 侵略的", "Aggressive behavior.", 3, 70, "考纲词", "考研"),
    ("alert", "/əˈlɜːrt/", "adj. 警觉的", "Stay alert.", 3, 70, "考纲词", "考研"),
    ("alien", "/ˈeɪliən/", "adj. 外国的", "Alien culture.", 3, 68, "考纲词", "考研"),
    ("allege", "/əˈledʒ/", "v. 声称", "Allege the facts.", 3, 68, "考纲词", "考研"),
    ("alleviate", "/əˈliːvieɪt/", "v. 减轻", "Alleviate poverty.", 3, 70, "考纲词", "考研"),
    ("alliance", "/əˈlaɪəns/", "n. 联盟", "Form an alliance.", 3, 70, "考纲词", "考研"),
    ("allocate", "/ˈæləkeɪt/", "v. 分配", "Allocate funds.", 3, 70, "考纲词", "考研"),
    ("allowance", "/əˈlaʊəns/", "n. 津贴", "Monthly allowance.", 3, 68, "考纲词", "考研"),
    ("allude", "/əˈluːd/", "v. 暗指", "Allude to the issue.", 3, 66, "考纲词", "考研"),
    ("allure", "/əˈlʊr/", "n. 诱惑", "The allure of fame.", 3, 68, "考纲词", "考研"),
    ("ally", "/ˈælaɪ/", "n. 盟友", "Political ally.", 3, 68, "考纲词", "考研"),
    ("alternate", "/ˈɔːltərnət/", "v. 交替", "Alternate between.", 3, 70, "考纲词", "考研"),
    ("alternative", "/ɔːlˈtɜːrnətɪv/", "n. 替代", "Alternative solution.", 3, 72, "考纲词", "考研"),
    ("altitude", "/ˈæltɪtuːd/", "n. 高度", "High altitude.", 3, 68, "考纲词", "考研"),
    ("amateur", "/ˈæmətər/", "n. 业余爱好者", "Amateur photographer.", 3, 68, "考纲词", "考研"),
    ("ambassador", "/æmˈbæsədər/", "n. 大使", "Ambassador to China.", 3, 68, "考纲词", "考研"),
    ("ambiguous", "/æmˈbɪɡjuəs/", "adj. 模糊的", "Ambiguous statement.", 3, 72, "考纲词", "考研"),
    ("ambitious", "/æmˈbɪʃəs/", "adj. 有野心的", "Ambitious plan.", 3, 70, "考纲词", "考研"),
    ("amplify", "/ˈæmplɪfaɪ/", "v. 放大", "Amplify the sound.", 3, 70, "考纲词", "考研"),
    ("analogous", "/əˈnæləɡəs/", "adj. 类似的", "Analogous situation.", 3, 70, "考纲词", "考研"),
    ("analogy", "/əˈnælədʒi/", "n. 类比", "Draw an analogy.", 3, 70, "考纲词", "考研"),
    ("analytical", "/ˌænəˈlɪtɪkl/", "adj. 分析的", "Analytical skills.", 3, 72, "考纲词", "考研"),
    ("anecdote", "/ˈænɪkdoʊt/", "n. 轶事", "Interesting anecdote.", 3, 68, "考纲词", "考研"),
    ("anguish", "/ˈæŋɡwɪʃ/", "n. 痛苦", "Mental anguish.", 3, 66, "考纲词", "考研"),
    ("animated", "/ˈænɪmeɪtɪd/", "adj. 生动的", "Animated discussion.", 3, 70, "考纲词", "考研"),
    ("annotate", "/ˈænəteɪt/", "v. 注释", "Annotate the text.", 3, 68, "考纲词", "考研"),
    ("anonymous", "/əˈnɑːnɪməs/", "adj. 匿名的", "Anonymous letter.", 3, 70, "考纲词", "考研"),
    ("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期", "Anticipate changes.", 3, 72, "考纲词", "考研"),
    ("antique", "/ænˈtiːk/", "adj. 古老的", "Antique furniture.", 3, 68, "考纲词", "考研"),
    ("apex", "/ˈeɪpeks/", "n. 顶点", "Apex of career.", 3, 66, "考纲词", "考研"),
    ("apparatus", "/ˌæpəˈrætəs/", "n. 器械", "Medical apparatus.", 3, 66, "考纲词", "考研"),
    ("appeal", "/əˈpiːl/", "n. 呼吁", "Appeal for help.", 3, 72, "考纲词", "考研"),
    ("appetite", "/ˈæpɪtaɪt/", "n. 食欲", "Healthy appetite.", 3, 68, "考纲词", "考研"),
    ("applaud", "/əˈplɔːd/", "v. 鼓掌", "Applaud the speaker.", 3, 68, "考纲词", "考研"),
    ("appraise", "/əˈpreɪz/", "v. 评价", "Appraise the work.", 3, 70, "考纲词", "考研"),
    ("apprehensive", "/ˌæprɪˈhensɪv/", "adj. 担心的", "Apprehensive about future.", 3, 70, "考纲词", "考研"),
    ("aptitude", "/ˈæptɪtuːd/", "n. 才能", "Natural aptitude.", 3, 70, "考纲词", "考研"),
    ("architect", "/ˈɑːrkɪtekt/", "n. 建筑师", "Famous architect.", 3, 68, "考纲词", "考研"),
    ("architecture", "/ˈɑːrkɪtektʃər/", "n. 建筑", "Modern architecture.", 3, 70, "考纲词", "考研"),
    ("ardent", "/ˈɑːrdnt/", "adj. 热情的", "Ardent supporter.", 3, 68, "考纲词", "考研"),
    ("arithmetic", "/əˈrɪθmətɪk/", "n. 算术", "Basic arithmetic.", 3, 68, "考纲词", "考研"),
    ("arouse", "/əˈraʊz/", "v. 唤起", "Arouse interest.", 3, 70, "考纲词", "考研"),
    ("array", "/əˈreɪ/", "n. 阵列", "Array of data.", 3, 70, "考纲词", "考研"),
    ("arrest", "/əˈrest/", "v. 逮捕", "Arrest the suspect.", 3, 70, "考纲词", "考研"),
    ("arrogant", "/ˈærəɡənt/", "adj. 傲慢的", "Arrogant attitude.", 3, 70, "考纲词", "考研"),
    ("arsenal", "/ˈɑːrsənl/", "n. 军火库", "Military arsenal.", 3, 66, "考纲词", "考研"),
    ("artificial", "/ˌɑːrtɪˈfɪʃl/", "adj. 人造的", "Artificial intelligence.", 3, 72, "考纲词", "考研"),
    ("artifact", "/ˈɑːrtɪfækt/", "n. 人工制品", "Ancient artifact.", 3, 68, "考纲词", "考研"),
    ("artisan", "/ˈɑːrtəzn/", "n. 工匠", "Skilled artisan.", 3, 66, "考纲词", "考研"),
    ("articulate", "/ɑːrˈtɪkjəleɪt/", "v. 清晰表达", "Articulate ideas.", 3, 72, "考纲词", "考研"),
    ("ascend", "/əˈsend/", "v. 上升", "Ascend the mountain.", 3, 68, "考纲词", "考研"),
    ("ascertain", "/ˌæsərˈteɪn/", "v. 确定", "Ascertain the facts.", 3, 70, "考纲词", "考研"),
    ("ascribe", "/əˈskraɪb/", "v. 归因于", "Ascribe to effort.", 3, 70, "考纲词", "考研"),
    ("ashamed", "/əˈʃeɪmd/", "adj. 羞愧的", "Feel ashamed.", 3, 68, "考纲词", "考研"),
    ("aspiration", "/ˌæspəˈreɪʃn/", "n. 抱负", "Career aspiration.", 3, 70, "考纲词", "考研"),
    ("aspire", "/əˈspaɪər/", "v. 渴望", "Aspire to success.", 3, 70, "考纲词", "考研"),
    ("assassinate", "/əˈsæsəneɪt/", "v. 暗杀", "Assassinate the leader.", 3, 66, "考纲词", "考研"),
    ("assault", "/əˈsɔːlt/", "n. 攻击", "Physical assault.", 3, 68, "考纲词", "考研"),
    ("assemble", "/əˈsembl/", "v. 集合", "Assemble the team.", 3, 70, "考纲词", "考研"),
    ("assert", "/əˈsɜːrt/", "v. 断言", "Assert one's rights.", 3, 70, "考纲词", "考研"),
    ("assess", "/əˈses/", "v. 评估", "Assess the damage.", 3, 70, "考纲词", "考研"),
    ("asset", "/ˈæset/", "n. 资产", "Valuable asset.", 3, 70, "考纲词", "考研"),
    ("assimilate", "/əˈsɪməleɪt/", "v. 吸收", "Assimilate knowledge.", 3, 70, "考纲词", "考研"),
    ("assorted", "/əˈsɔːrtɪd/", "adj. 各种各样的", "Assorted goods.", 3, 68, "考纲词", "考研"),
    ("astound", "/əˈstaʊnd/", "v. 使震惊", "Astound everyone.", 3, 68, "考纲词", "考研"),
    ("astronaut", "/ˈæstrənɔːt/", "n. 宇航员", "Space astronaut.", 3, 68, "考纲词", "考研"),
    ("astronomy", "/əˈstrɑːnəmi/", "n. 天文学", "Study astronomy.", 3, 68, "考纲词", "考研"),
    ("asylum", "/əˈsaɪləm/", "n. 庇护", "Political asylum.", 3, 66, "考纲词", "考研"),
    ("atlas", "/ˈætləs/", "n. 地图集", "World atlas.", 3, 66, "考纲词", "考研"),
    ("atomic", "/əˈtɒmɪk/", "adj. 原子的", "Atomic bomb.", 3, 70, "考纲词", "考研"),
    ("attain", "/əˈteɪn/", "v. 达到", "Attain the goal.", 3, 70, "考纲词", "考研"),
    ("attentive", "/əˈtentɪv/", "adj. 专心的", "Attentive student.", 3, 70, "考纲词", "考研"),
    ("attorney", "/əˈtɜːrni/", "n. 律师", "Legal attorney.", 3, 68, "考纲词", "考研"),
    ("attribute", "/əˈtrɪbjuːt/", "v. 归因于", "Attribute to success.", 3, 72, "考纲词", "考研"),
    ("audit", "/ˈɔːdɪt/", "n. 审计", "Financial audit.", 3, 70, "考纲词", "考研"),
    ("auditorium", "/ˌɔːdɪˈtɔːriəm/", "n. 礼堂", "School auditorium.", 3, 66, "考纲词", "考研"),
    ("augment", "/ɔːɡˈment/", "v. 增加", "Augment resources.", 3, 68, "考纲词", "考研"),
    ("authority", "/əˈθɔːrəti/", "n. 权威", "Local authority.", 3, 70, "考纲词", "考研"),
    ("autonomous", "/ɔːˈtɑːnəməs/", "adj. 自治的", "Autonomous region.", 3, 70, "考纲词", "考研"),
    ("automate", "/ˈɔːtəmeɪt/", "v. 自动化", "Automate the process.", 3, 70, "考纲词", "考研"),
    ("avail", "/əˈveɪl/", "v. 利用", "Avail of opportunity.", 3, 66, "考纲词", "考研"),
    ("avert", "/əˈvɜːrt/", "v. 避免", "Avert disaster.", 3, 66, "考纲词", "考研"),
    ("aviation", "/ˌeɪviˈeɪʃn/", "n. 航空", "Civil aviation.", 3, 68, "考纲词", "考研"),
]


def init_words():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    try:
        db.query(Word).delete()
        db.commit()

        all_words = {}

        for word_data in CET4_WORDS:
            all_words[word_data[0]] = word_data

        for word_data in CET6_WORDS:
            if word_data[0] not in all_words:
                all_words[word_data[0]] = word_data

        for word_data in GRADUATE_WORDS:
            if word_data[0] not in all_words:
                all_words[word_data[0]] = word_data

        added_count = 0
        for word_data in all_words.values():
            word = Word(
                word=word_data[0],
                phonetic=word_data[1],
                meaning=word_data[2],
                example_sentence=word_data[3],
                difficulty=word_data[4],
                frequency=word_data[5],
                exam_requirement=word_data[6],
                category=word_data[7]
            )
            db.add(word)
            added_count += 1

        db.commit()
        print("词汇数据初始化完成！")
        print(f"新增词汇: {added_count}")
        print(f"CET-4词汇总数: {len([w for w in db.query(Word).filter(Word.category == 'CET-4').all()])}")
        print(f"CET-6词汇总数: {len([w for w in db.query(Word).filter(Word.category == 'CET-6').all()])}")
        print(f"考研词汇总数: {len([w for w in db.query(Word).filter(Word.category == '考研').all()])}")
    except Exception as e:
        db.rollback()
        print(f"初始化失败: {e}")
    finally:
        db.close()


if __name__ == "__main__":
    init_words()